"""Add file path to source

Revision ID: 1a44c0891c33
Revises: 4feb443aebc7
Create Date: 2015-10-20 02:49:49.779000

"""

# revision identifiers, used by Alembic.
revision = '1a44c0891c33'
down_revision = '4feb443aebc7'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'visible',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.add_column('source', sa.Column('file_path', sa.String(length=512), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('source', 'file_path')
    op.alter_column('event', 'visible',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    ### end Alembic commands ###
