"""empty message

Revision ID: 2b03da297225
Revises: 305768117feb
Create Date: 2015-10-21 06:07:04.177000

"""

# revision identifiers, used by Alembic.
revision = '2b03da297225'
down_revision = '305768117feb'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('token', table_name='player')
    op.create_index(op.f('ix_player_token'), 'player', ['token'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('token', 'player', ['token'], unique=True)
    op.drop_index(op.f('ix_player_token'), table_name='player')
    ### end Alembic commands ###
