"""empty message

Revision ID: 4128ac7c807e
Revises: 47d027ef810e
Create Date: 2015-10-24 04:08:47.460000

"""

# revision identifiers, used by Alembic.
revision = '4128ac7c807e'
down_revision = '47d027ef810e'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'visible',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.drop_column('media', 'played')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('played', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.alter_column('event', 'visible',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    ### end Alembic commands ###
