"""empty message

Revision ID: 47d027ef810e
Revises: 2410fe90d63d
Create Date: 2015-10-23 01:32:33.277000

"""

# revision identifiers, used by Alembic.
revision = '47d027ef810e'
down_revision = '2410fe90d63d'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'visible',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('media', 'played',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.add_column('source', sa.Column('file_name', sa.String(length=256), nullable=True))
    op.drop_column('source', 'file_path')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source', sa.Column('file_path', mysql.VARCHAR(length=512), nullable=True))
    op.drop_column('source', 'file_name')
    op.alter_column('media', 'played',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('event', 'visible',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    ### end Alembic commands ###
