"""empty message

Revision ID: 7f5335fbf03
Revises: 2b03da297225
Create Date: 2015-10-22 20:25:56.086000

"""

# revision identifiers, used by Alembic.
revision = '7f5335fbf03'
down_revision = '2b03da297225'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'visible',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.add_column('media', sa.Column('played', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media', 'played')
    op.alter_column('event', 'visible',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    ### end Alembic commands ###
